name: Build and Release

# イベントトリガー：タグがpushされたときに実行
on:
  push:
    tags:
      - 'v*'  # vから始まるタグ (例: v0.1.0)
    branches:
      - '**'  # すべてのブランチへのプッシュ
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --name disk_utility src/main.py
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: disk_utility
          path: dist/disk_utility 