name: Create New Release

on:
  workflow_run:
    workflows: ["Build and Release"]
    types:
      - completed
    branches:
      - main
      - master

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get current version
        id: get_version
        run: |
          # 最新のタグを取得
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"
          
          # バージョン番号を分割
          VERSION_PARTS=(${LATEST_TAG#v})
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          
          # パッチバージョンをインクリメント
          NEW_PATCH=$((PATCH + 1))
          NEW_TAG="v$MAJOR.$MINOR.$NEW_PATCH"
          
          echo "New tag: $NEW_TAG"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
      
      - name: Create new tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag ${{ steps.get_version.outputs.new_tag }}
          git push origin ${{ steps.get_version.outputs.new_tag }}
      
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: disk_utility
          path: dist
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.new_tag }}
          name: Release ${{ steps.get_version.outputs.new_tag }}
          files: dist/disk_utility
          body: |
            ## 機能と改善点
            
            - ReFSファイルシステムのサポートを追加
            - ディスク操作の安全性を向上
            - エラーメッセージの改善
            - テストカバレッジの向上
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 